In [4]:
import yfinance as yf

In [5]:
ticker = yf.Ticker('AAPL')

In [6]:
# use ?? for info
??yf.Ticker

Init signature: yf.Ticker(ticker, session=None)
Docstring:      <no docstring>
Source:
class Ticker(TickerBase):
    def __init__(self, ticker, session=None):
        super(Ticker, self).__init__(ticker, session=session)
        self._expirations = {}
        self._underlying  = {}

    def __repr__(self):
        return f'yfinance.Ticker object <{self.ticker}>'

    def _download_options(self, date=None):
        if date is None:
            url = f"{_BASE_URL_}/v7/finance/options/{self.ticker}"
        else:
            url = f"{_BASE_URL_}/v7/finance/options/{self.ticker}?date={date}"

        r = self._data.get(url=url).json()
        if len(r.get('optionChain', {}).get('result', [])) > 0:
            for exp in r['optionChain']['result'][0]['expirationDates']:
                self._expirations[_pd.Timestamp(exp, unit='s').strftime('%Y-%m-%d')] = exp

            self._underlying = r['optionChain']['result'][0].get('quote', {})

            opt = r['optionChain']['result'][0].get('options', [])

            return dict(**opt[0],underlying=self._underlying) if len(opt) > 0 else {}
        return {}

    def _options2df(self, opt, tz=None):
        data = _pd.DataFrame(opt).reindex(columns=[
            'contractSymbol',
            'lastTradeDate',
            'strike',
            'lastPrice',
            'bid',
            'ask',
            'change',
            'percentChange',
            'volume',
            'openInterest',
            'impliedVolatility',
            'inTheMoney',
            'contractSize',
            'currency'])

        data['lastTradeDate'] = _pd.to_datetime(
            data['lastTradeDate'], unit='s', utc=True)
        if tz is not None:
            data['lastTradeDate'] = data['lastTradeDate'].dt.tz_convert(tz)
        return data

    def option_chain(self, date=None, tz=None):
        if date is None:
            options = self._download_options()
        else:
            if not self._expirations:
                self._download_options()
            if date not in self._expirations:
                raise ValueError(
                    f"Expiration `{date}` cannot be found. "
                    f"Available expirations are: [{', '.join(self._expirations)}]")
            date = self._expirations[date]
            options = self._download_options(date)

        if not options:
            return _namedtuple('Options', ['calls', 'puts', 'underlying'])(**{
                "calls": None, "puts": None, "underlying": None
            })

        return _namedtuple('Options', ['calls', 'puts', 'underlying'])(**{
            "calls": self._options2df(options['calls'], tz=tz),
            "puts": self._options2df(options['puts'], tz=tz),
            "underlying": options['underlying']
        })

    # ------------------------

    @property
    def isin(self):
        return self.get_isin()

    @property
    def major_holders(self) -> _pd.DataFrame:
        return self.get_major_holders()

    @property
    def institutional_holders(self) -> _pd.DataFrame:
        return self.get_institutional_holders()

    @property
    def mutualfund_holders(self) -> _pd.DataFrame:
        return self.get_mutualfund_holders()

    @property
    def insider_purchases(self) -> _pd.DataFrame:
        return self.get_insider_purchases()

    @property
    def insider_transactions(self) -> _pd.DataFrame:
        return self.get_insider_transactions()

    @property
    def insider_roster_holders(self) -> _pd.DataFrame:
        return self.get_insider_roster_holders()

    @property
    def dividends(self) -> _pd.Series:
        return self.get_dividends()

    @property
    def capital_gains(self) -> _pd.Series:
        return self.get_capital_gains()

    @property
    def splits(self) -> _pd.Series:
        return self.get_splits()

    @property
    def actions(self) -> _pd.DataFrame:
        return self.get_actions()

    @property
    def shares(self) -> _pd.DataFrame:
        return self.get_shares()

    @property
    def info(self) -> dict:
        return self.get_info()

    @property
    def fast_info(self):
        return self.get_fast_info()

    @property
    def valuation(self) -> _pd.DataFrame:
        return self.get_valuation_measures()

    @property
    def calendar(self) -> dict:
        """
        Returns a dictionary of events, earnings, and dividends for the ticker
        """
        return self.get_calendar()

    @property
    def sec_filings(self) -> dict:
        return self.get_sec_filings()

    @property
    def recommendations(self):
        return self.get_recommendations()

    @property
    def recommendations_summary(self):
        return self.get_recommendations_summary()

    @property
    def upgrades_downgrades(self):
        return self.get_upgrades_downgrades()

    @property
    def earnings(self) -> _pd.DataFrame:
        return self.get_earnings()

    @property
    def quarterly_earnings(self) -> _pd.DataFrame:
        return self.get_earnings(freq='quarterly')

    @property
    def income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True)

    @property
    def quarterly_income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True, freq='quarterly')

    @property
    def ttm_income_stmt(self) -> _pd.DataFrame:
        return self.get_income_stmt(pretty=True, freq='trailing')

    @property
    def incomestmt(self) -> _pd.DataFrame:
        return self.income_stmt

    @property
    def quarterly_incomestmt(self) -> _pd.DataFrame:
        return self.quarterly_income_stmt

    @property
    def ttm_incomestmt(self) -> _pd.DataFrame:
        return self.ttm_income_stmt

    @property
    def financials(self) -> _pd.DataFrame:
        return self.income_stmt

    @property
    def quarterly_financials(self) -> _pd.DataFrame:
        return self.quarterly_income_stmt

    @property
    def ttm_financials(self) -> _pd.DataFrame:
        return self.ttm_income_stmt

    @property
    def balance_sheet(self) -> _pd.DataFrame:
        return self.get_balance_sheet(pretty=True)

    @property
    def quarterly_balance_sheet(self) -> _pd.DataFrame:
        return self.get_balance_sheet(pretty=True, freq='quarterly')

    @property
    def balancesheet(self) -> _pd.DataFrame:
        return self.balance_sheet

    @property
    def quarterly_balancesheet(self) -> _pd.DataFrame:
        return self.quarterly_balance_sheet

    @property
    def cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq="yearly")

    @property
    def quarterly_cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq='quarterly')

    @property
    def ttm_cash_flow(self) -> _pd.DataFrame:
        return self.get_cash_flow(pretty=True, freq='trailing')

    @property
    def cashflow(self) -> _pd.DataFrame:
        return self.cash_flow

    @property
    def quarterly_cashflow(self) -> _pd.DataFrame:
        return self.quarterly_cash_flow

    @property
    def ttm_cashflow(self) -> _pd.DataFrame:
        return self.ttm_cash_flow

    @property
    def analyst_price_targets(self) -> dict:
        return self.get_analyst_price_targets()

    @property
    def earnings_estimate(self) -> _pd.DataFrame:
        return self.get_earnings_estimate()

    @property
    def revenue_estimate(self) -> _pd.DataFrame:
        return self.get_revenue_estimate()

    @property
    def earnings_history(self) -> _pd.DataFrame:
        return self.get_earnings_history()

    @property
    def eps_trend(self) -> _pd.DataFrame:
        return self.get_eps_trend()

    @property
    def eps_revisions(self) -> _pd.DataFrame:
        return self.get_eps_revisions()

    @property
    def growth_estimates(self) -> _pd.DataFrame:
        return self.get_growth_estimates()

    @property
    def sustainability(self) -> _pd.DataFrame:
        return self.get_sustainability()

    @property
    def options(self) -> tuple:
        if not self._expirations:
            self._download_options()
        return tuple(self._expirations.keys())

    @property
    def news(self) -> list:
        return self.get_news()

    @property
    def earnings_dates(self) -> _pd.DataFrame:
        return self.get_earnings_dates()

    @property
    def history_metadata(self) -> dict:
        return self.get_history_metadata()

    @property
    def funds_data(self) -> FundsData:
        return self.get_funds_data()
File:           c:\users\diamo\desktop\tradingbot\trading_env\lib\site-packages\yfinance\ticker.py
Type:           type
Subclasses:

In [7]:
ticker.info["zip"]

'95014'

In [8]:
ticker.analyst_price_targets

{'current': 312.06,
 'high': 400.0,
 'low': 215.0,
 'mean': 310.507,
 'median': 310.0}

In [9]:
# returns a pandas dataframe
ticker.quarterly_balance_sheet

,2026-03-31,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Ordinary Shares Number,1.466769e+10,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,NaN,NaN
Share Issued,1.466769e+10,1.469793e+10,1.477326e+10,1.485672e+10,1.493932e+10,NaN,NaN
Net Debt,3.913900e+10,4.519200e+10,6.272300e+10,6.542900e+10,7.002400e+10,NaN,NaN
Total Debt,8.471100e+10,9.050900e+10,9.865700e+10,1.016980e+11,9.818600e+10,NaN,NaN
Tangible Book Value,8.515700e+10,8.819000e+10,7.373300e+10,6.583000e+10,6.679600e+10,NaN,NaN
...,...,...,...,...,...,...,...
Cash Cash Equivalents And Short Term Investments,6.850700e+10,6.690700e+10,5.469700e+10,5.537200e+10,4.849800e+10,NaN,NaN
Other Short Term Investments,2.293500e+10,2.159000e+10,1.876300e+10,1.910300e+10,2.033600e+10,NaN,NaN
Cash And Cash Equivalents,4.557200e+10,4.531700e+10,3.593400e+10,3.626900e+10,2.816200e+10,NaN,NaN
Cash Equivalents,1.583200e+10,1.449100e+10,7.667000e+09,9.583000e+09,3.101000e+09,NaN,NaN
Cash Financial,2.974000e+10,3.082600e+10,2.826700e+10,2.668600e+10,2.506100e+10,NaN,NaN

In [10]:
ticker.news

[{'id': '367fa6dc-1e0e-42a0-b4de-df2de871d7d0',
  'content': {'id': '367fa6dc-1e0e-42a0-b4de-df2de871d7d0',
   'contentType': 'VIDEO',
   'title': 'AI spending fervor is comparable to industrial push during World War 2',
   'description': '<p>Zacks Investment Research senior stock strategist Andrew Rocco comments on the heightened spending seen across the AI trade — particularly in the memory chip landscape amid shortages — comparing to prior buildouts in American history.</p>',
   'summary': 'Zacks Investment Research senior stock strategist Andrew Rocco comments on the heightened spending seen across the AI trade — particularly in the memory chip landscape amid shortages — comparing to prior buildouts in American history.',
   'pubDate': '2026-05-29T12:00:00Z',
   'displayTime': '',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://s.yimg.com/uu/api/res/1.2/Nga6jdVXYmCazZ73orKSWA--~B/aD0xODU5O3c9MzMwNTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/7fce2143-234f-4ca3-a237-66f961c8d46f_3273fa62342428623bd095586863a195cdc009674c8515f170dec5e5031d5578.jpg',
    'originalWidth': 3305,
    'originalHeight': 1859,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/Nga6jdVXYmCazZ73orKSWA--~B/aD0xODU5O3c9MzMwNTthcHBpZD15dGFjaHlvbg--/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/7fce2143-234f-4ca3-a237-66f961c8d46f_3273fa62342428623bd095586863a195cdc009674c8515f170dec5e5031d5578.jpg',
      'width': 3305,
      'height': 1859,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/y7Sz7hgLFfJwkybzUv94Eg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://d29szjachogqwa.cloudfront.net/images/user-uploaded/7fce2143-234f-4ca3-a237-66f961c8d46f_3273fa62342428623bd095586863a195cdc009674c8515f170dec5e5031d5578.jpg',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Yahoo Finance Video',
    'url': 'https://finance.yahoo.com/',
    'sourceId': 'video.yahoofinance.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/video/ai-spending-fervor-comparable-industrial-120000048.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/video/ai-spending-fervor-comparable-industrial-120000048.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': True},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '6f1bd174-9b72-372d-9581-ae21aee77bb9',
  'content': {'id': '6f1bd174-9b72-372d-9581-ae21aee77bb9',
   'contentType': 'STORY',
   'title': 'These 2 Tech Titans Just Declared Dividend Raises. Should You Buy One or Both?',
   'description': '',
   'summary': 'One of the pair is boosting its payout 25-fold.',
   'pubDate': '2026-05-29T21:20:00Z',
   'displayTime': '2026-05-29T21:20:00Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/c951f7413fb1265a62fc4f9b3a99c5cd',
    'originalWidth': 1400,
    'originalHeight': 933,
    'caption': 'Two people shake hands while a third looks on happily.',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/N2voJ5BYRhxb.J5Idq9RLQ--~B/aD05MzM7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/c951f7413fb1265a62fc4f9b3a99c5cd',
      'width': 1400,
      'height': 933,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/fHVxMBGxF_Tl_cegu7YyNg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/c951f7413fb1265a62fc4f9b3a99c5cd',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/investing/2026/05/29/these-2-tech-titans-just-declared-dividend-raises/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/2-tech-titans-just-declared-212000553.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '4a06c692-31d2-3103-a77e-e369976655cd',
  'content': {'id': '4a06c692-31d2-3103-a77e-e369976655cd',
   'contentType': 'STORY',
   'title': 'Apple AI Shift And Huawei Chips Test Valuation And Growth Expectations',
   'description': '',
   'summary': "Apple announced AI-driven accessibility upgrades across its devices and plans a major Siri overhaul that will make artificial intelligence more central to everyday use. The company is rolling out these features as Huawei introduces its LogicFolding semiconductor approach, raising competitive pressure in China's premium smartphone market. These developments come as NasdaqGS:AAPL trades at $312.51, with the stock up 2.5% over the past week and 56.9% over the past year. Recent AI...",
   'pubDate': '2026-05-29T21:10:06Z',
   'displayTime': '2026-05-29T21:10:06Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/simply_wall_st__316/69084628647944e382f8e555f97913e8',
    'originalWidth': 1194,
    'originalHeight': 432,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/fBnY8upz5XxbZDDWlufZ9w--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/69084628647944e382f8e555f97913e8',
      'width': 1194,
      'height': 432,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/bU5AIomYRBg3WBNqAswADg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/simply_wall_st__316/69084628647944e382f8e555f97913e8',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Simply Wall St.',
    'url': 'https://simplywall.st/',
    'sourceId': 'simply_wall_st__316'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-ai-shift-huawei-chips-211006997.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-ai-shift-huawei-chips-211006997.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'ef9a1540-8c0f-3197-8de6-1c6d0b969f15',
  'content': {'id': 'ef9a1540-8c0f-3197-8de6-1c6d0b969f15',
   'contentType': 'STORY',
   'title': 'The Memory Shortage Is Just Beginning. The Consumer Pain Is Already Here.',
   'description': '',
   'summary': 'Memory prices for PCs, smartphones, and gaming consoles are spiking. Consumers will bear the brunt of the inflation.',
   'pubDate': '2026-05-29T20:46:00Z',
   'displayTime': '2026-05-29T20:46:00Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/ef9a1540-8c0f-3197-8de6-1c6d0b969f15/the-memory-shortage-is-just.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Barrons.com/aeb5987f7aa86bc4ed743ba9c481c329',
    'originalWidth': 1280,
    'originalHeight': 640,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/8KU628JoGi4OtoPvU4z5JA--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/aeb5987f7aa86bc4ed743ba9c481c329',
      'width': 1280,
      'height': 640,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/bGzyBr4aBnknDvlvaqKaCg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Barrons.com/aeb5987f7aa86bc4ed743ba9c481c329',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Barrons.com',
    'url': 'http://www.barrons.com/',
    'sourceId': 'Barrons.com'},
   'canonicalUrl': {'url': 'https://www.barrons.com/articles/memory-chip-shortage-inflation-dell-micron-stock-928d0542?siteid=yhoof2&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '9c1a9856-4c36-3693-87a1-8d4ccb76fb62',
  'content': {'id': '9c1a9856-4c36-3693-87a1-8d4ccb76fb62',
   'contentType': 'STORY',
   'title': 'Sell in May? You Would’ve Missed One of the S&P 500’s Best Mays Since the ‘50s.',
   'description': '',
   'summary': 'The S&P 500, driven by tech stocks, is on pace to power more than 5% higher this month, marking one of the best performances in May since the 1950s.',
   'pubDate': '2026-05-29T16:15:00Z',
   'displayTime': '2026-05-29T16:15:00Z',
   'isHosted': False,
   'bypassModal': False,
   'previewUrl': 'https://finance.yahoo.com/m/9c1a9856-4c36-3693-87a1-8d4ccb76fb62/sell-in-may-you-would%E2%80%99ve.html',
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/Barrons.com/898d3cf9e8a097c6898c67a9f7f4dd85',
    'originalWidth': 1280,
    'originalHeight': 640,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/ZFZAhnVV4VwxMZ4BoEHbyA--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/898d3cf9e8a097c6898c67a9f7f4dd85',
      'width': 1280,
      'height': 640,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/ZJXvKzD5byMZd6XdtCYwBQ--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/Barrons.com/898d3cf9e8a097c6898c67a9f7f4dd85',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Barrons.com',
    'url': 'http://www.barrons.com/',
    'sourceId': 'Barrons.com'},
   'canonicalUrl': {'url': 'https://www.barrons.com/articles/stock-market-tech-micron-nvidia-amd-4803938b?siteid=yhoof2&yptr=yahoo',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': None,
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '30b0e9fc-48d3-3f04-aa12-8afb9693b5e4',
  'content': {'id': '30b0e9fc-48d3-3f04-aa12-8afb9693b5e4',
   'contentType': 'STORY',
   'title': 'RPG Investment Advisory Reduces Peabody Energy Stake, According to Recent SEC Filing',
   'description': '',
   'summary': 'Peabody is more than a power-generation coal producer. Its growth potential relies on Centurion, an Australian mine that must deliver more consistent steelmaking coal earnings.',
   'pubDate': '2026-05-29T16:08:45Z',
   'displayTime': '2026-05-29T16:08:45Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/motleyfool.com/e1ee430ed22ebe173d4eb7447a20e7be',
    'originalWidth': 800,
    'originalHeight': 714,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/7Jt_CzsFLtVR2c79MHlSDQ--~B/aD03MTQ7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/e1ee430ed22ebe173d4eb7447a20e7be',
      'width': 800,
      'height': 714,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/xNxz4ZIdOFx2xrU_eHapgw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/motleyfool.com/e1ee430ed22ebe173d4eb7447a20e7be',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Motley Fool',
    'url': 'http://www.fool.com/',
    'sourceId': 'motleyfool.com'},
   'canonicalUrl': {'url': 'https://www.fool.com/coverage/filings/2026/05/29/rpg-investment-advisory-reduces-peabody-energy-stake-according-to-recent-sec-filing/',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/rpg-investment-advisory-reduces-peabody-160845040.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '572ce837-6c35-355d-b29a-30b0945586e5',
  'content': {'id': '572ce837-6c35-355d-b29a-30b0945586e5',
   'contentType': 'STORY',
   'title': 'Apple (AAPL) is a Great Momentum Stock: Should You Buy?',
   'description': '',
   'summary': "Does Apple (AAPL) have what it takes to be a top stock pick for momentum investors? Let's find out.",
   'pubDate': '2026-05-29T16:00:03Z',
   'displayTime': '2026-05-29T16:00:03Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/zacks.com/ac90b3d74679f6d01a122aa033d8a9a4',
    'originalWidth': 900,
    'originalHeight': 600,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/9naTdeJlVMX28sdlDpLdrQ--~B/aD02MDA7dz05MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/zacks.com/ac90b3d74679f6d01a122aa033d8a9a4',
      'width': 900,
      'height': 600,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/FPwXGsyxPV4rpg4GqtBI5w--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/zacks.com/ac90b3d74679f6d01a122aa033d8a9a4',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Zacks',
    'url': 'http://www.zacks.com/',
    'sourceId': 'zacks.com'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-aapl-great-momentum-stock-160003753.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/apple-aapl-great-momentum-stock-160003753.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '802045a4-1a11-32c0-a850-ad6691d47ec8',
  'content': {'id': '802045a4-1a11-32c0-a850-ad6691d47ec8',
   'contentType': 'STORY',
   'title': '3 Dow Jones Stocks to Consider Right Now',
   'description': '',
   'summary': 'The Dow Jones (^DJI) is packed with iconic businesses that have built strong brands and durable market positions. A select few continue to thrive, delivering solid returns and proving their resilience in an evolving market.',
   'pubDate': '2026-05-29T15:44:38Z',
   'displayTime': '2026-05-29T15:44:38Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/stockstory_922/32591b77a8ad02eacdfd8a45d8896448',
    'originalWidth': 1400,
    'originalHeight': 700,
    'caption': 'AAPL Cover Image',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/CAhBj8O7fJ6i2BC9JUcJ.Q--~B/aD03MDA7dz0xNDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/stockstory_922/32591b77a8ad02eacdfd8a45d8896448',
      'width': 1400,
      'height': 700,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/_OH7BsaJvzZzMyuZZdyvNw--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/stockstory_922/32591b77a8ad02eacdfd8a45d8896448',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'StockStory',
    'url': 'https://stockstory.org/',
    'sourceId': 'stockstory_922'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/3-dow-jones-stocks-consider-154438483.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/3-dow-jones-stocks-consider-154438483.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': '0f37f73e-de3b-3da4-9428-a8aa860b848a',
  'content': {'id': '0f37f73e-de3b-3da4-9428-a8aa860b848a',
   'contentType': 'STORY',
   'title': 'TikTok Pushes Deeper Into Music as Label Relationships Shift',
   'description': '',
   'summary': 'TikTok restructures music operations while expanding direct artist tools and distribution infrastructure.',
   'pubDate': '2026-05-29T14:22:19Z',
   'displayTime': '2026-05-29T14:22:19Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': None,
   'provider': {'displayName': 'GuruFocus.com',
    'url': 'http://www.gurufocus.com/',
    'sourceId': 'us.finance.gurufocus'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/tiktok-pushes-deeper-music-label-142219644.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/sectors/technology/articles/tiktok-pushes-deeper-music-label-142219644.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}},
 {'id': 'ca2e6c32-e0e3-3a95-a584-27b095c0d587',
  'content': {'id': 'ca2e6c32-e0e3-3a95-a584-27b095c0d587',
   'contentType': 'STORY',
   'title': 'Hershey Bull Sees World Cup, America 250 Lifting Sales',
   'description': '',
   'summary': "(Bloomberg) -- Summer events including the FIFA World Cup and America’s 250th anniversary could spur sales of sweet treats, making now a key time to snap up beaten-down shares of Hershey Co., according to the candy and snack maker’s newest Wall Street bull.Most Read from BloombergSingapore Hands Byju's Founder His First Ever Jail TermApple to Overhaul iOS 27 Siri, AI Features: Here's a First PeekCVS Returns Zepbound to Drug Plans After Lilly Slashes PriceSpaceX Said to Cut IPO Value Goal to at L",
   'pubDate': '2026-05-29T14:17:31Z',
   'displayTime': '2026-05-29T14:17:31Z',
   'isHosted': True,
   'bypassModal': False,
   'previewUrl': None,
   'thumbnail': {'originalUrl': 'https://media.zenfs.com/en/bloomberg_holding_pen_162/de1e944b7f337e48b0767e83ba9e62d7',
    'originalWidth': 2010,
    'originalHeight': 1728,
    'caption': '',
    'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/o0Ujkz6PmFRBpTDFK9h10w--~B/aD0xNzI4O3c9MjAxMDthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/bloomberg_holding_pen_162/de1e944b7f337e48b0767e83ba9e62d7',
      'width': 2010,
      'height': 1728,
      'tag': 'original'},
     {'url': 'https://s.yimg.com/uu/api/res/1.2/WUmA4SiLG_GwMQ28dl0wsg--~B/Zmk9c3RyaW07aD0xMjg7dz0xNzA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/bloomberg_holding_pen_162/de1e944b7f337e48b0767e83ba9e62d7',
      'width': 170,
      'height': 128,
      'tag': '170x128'}]},
   'provider': {'displayName': 'Bloomberg',
    'url': 'https://www.bloomberg.com/company',
    'sourceId': 'bloomberg_holding_pen_162'},
   'canonicalUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/hershey-bull-sees-world-cup-141731161.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'clickThroughUrl': {'url': 'https://finance.yahoo.com/markets/stocks/articles/hershey-bull-sees-world-cup-141731161.html',
    'site': 'finance',
    'region': 'US',
    'lang': 'en-US'},
   'metadata': {'editorsPick': False},
   'finance': {'premiumFinance': {'isPremiumNews': False,
     'isPremiumFreeNews': False}},
   'storyline': None}}]

In [11]:
ticker.calendar

{'Dividend Date': datetime.date(2026, 5, 13),
 'Ex-Dividend Date': datetime.date(2026, 5, 10),
 'Earnings Date': [datetime.date(2026, 7, 30)],
 'Earnings High': 1.99,
 'Earnings Low': 1.83,
 'Earnings Average': 1.89541,
 'Revenue High': 112168000000,
 'Revenue Low': 107501000000,
 'Revenue Average': 109015606590}

In [12]:
df = ticker.history(period='ytd')
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-01-02 00:00:00-05:00,271.755128,277.324767,268.501164,270.507446,37838100,0.0,0.0
2026-01-05 00:00:00-05:00,270.138141,271.006523,265.646486,266.764404,45647200,0.0,0.0
2026-01-06 00:00:00-05:00,266.504884,267.053852,261.633929,261.873474,52352100,0.0,0.0
2026-01-07 00:00:00-05:00,262.711932,263.191023,259.328204,259.847229,48309800,0.0,0.0
2026-01-08 00:00:00-05:00,256.543358,258.809168,255.225814,258.559631,50419300,0.0,0.0
...,...,...,...,...,...,...,...
2026-05-22 00:00:00-04:00,306.119995,311.399994,305.839996,308.820007,43670200,0.0,0.0
2026-05-26 00:00:00-04:00,309.559998,311.820007,307.670013,308.329987,48000500,0.0,0.0
2026-05-27 00:00:00-04:00,308.329987,313.260010,308.299988,310.850006,50430900,0.0,0.0
2026-05-28 00:00:00-04:00,310.679993,312.799988,309.570007,312.510010,48220400,0.0,0.0
2026-05-29 00:00:00-04:00,311.774994,315.000000,309.529999,312.059998,56454230,0.0,0.0

In [13]:
df.iloc[1:20, [0,3]].head()

                                 Open       Close
Date
2026-01-05 00:00:00-05:00  270.138141  266.764404
2026-01-06 00:00:00-05:00  266.504884  261.873474
2026-01-07 00:00:00-05:00  262.711932  259.847229
2026-01-08 00:00:00-05:00  256.543358  258.559631
2026-01-09 00:00:00-05:00  258.599537  258.889008

In [14]:
ticker.option_chain(ticker.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,AAPL260529C00110000,2026-05-29 14:08:04+00:00,110.0,203.13,200.65,203.95,2.650009,1.321832,1,6,8.414067,True,REGULAR,USD
1,AAPL260529C00120000,2026-05-29 13:49:25+00:00,120.0,193.65,191.10,193.95,2.909988,1.525631,2,39,8.468755,True,REGULAR,USD
2,AAPL260529C00185000,2026-05-29 19:02:34+00:00,185.0,125.47,125.95,128.50,-1.510002,-1.189165,16,8,4.242192,True,REGULAR,USD
3,AAPL260529C00190000,2026-05-29 18:20:04+00:00,190.0,120.29,120.65,123.95,-1.790001,-1.466252,11,7,4.246098,True,REGULAR,USD
4,AAPL260529C00195000,2026-05-29 18:20:04+00:00,195.0,115.39,115.90,118.50,0.000000,0.000000,15,79,3.773438,True,REGULAR,USD
5,AAPL260529C00200000,2026-05-29 19:13:02+00:00,200.0,110.60,110.95,113.50,-1.120003,-1.002509,34,150,3.664063,True,REGULAR,USD
6,AAPL260529C00205000,2026-05-29 19:13:02+00:00,205.0,105.90,105.70,108.50,-0.919998,-0.861260,35,32,2.960940,True,REGULAR,USD
7,AAPL260529C00210000,2026-05-29 18:56:44+00:00,210.0,100.43,100.65,103.75,-0.870003,-0.858838,23,23,3.234377,True,REGULAR,USD
8,AAPL260529C00215000,2026-05-29 19:03:02+00:00,215.0,95.58,96.00,98.50,-0.159996,-0.167115,5,8,3.183596,True,REGULAR,USD
9,AAPL260529C00220000,2026-05-29 19:03:02+00:00,220.0,90.68,90.70,93.95,-0.629997,-0.689954,5,32,3.152346,True,REGULAR,USD
10,AAPL260529C00225000,2026-05-29 14:10:39+00:00,225.0,85.97,85.65,88.95,-0.599998,-0.693079,3,19,2.929690,True,REGULAR,USD
11,AAPL260529C00230000,2026-05-29 18:20:24+00:00,230.0,80.17,80.90,83.50,-1.500000,-1.836660,5,21,2.558597,True,REGULAR,USD
12,AAPL260529C00235000,2026-05-29 18:30:34+00:00,235.0,75.39,75.65,78.50,-1.510002,-1.963592,10,83,1.875001,True,REGULAR,USD
13,AAPL260529C00240000,2026-05-29 19:37:04+00:00,240.0,71.26,70.65,73.95,-0.889999,-1.233540,72,120,2.417973,True,REGULAR,USD
14,AAPL260529C00245000,2026-05-29 19:32:49+00:00,245.0,66.35,66.05,68.50,0.309998,0.469409,8,51,2.214848,True,REGULAR,USD
15,AAPL260529C00250000,2026-05-29 19:37:58+00:00,250.0,61.13,60.70,63.95,-0.570000,-0.923824,256,365,2.121098,True,REGULAR,USD
16,AAPL260529C00255000,2026-05-29 19:20:10+00:00,255.0,56.25,56.40,58.50,-1.349999,-2.343747,28,673,2.087895,True,REGULAR,USD
17,AAPL260529C00257500,2026-05-29 15:54:29+00:00,257.5,53.62,53.60,56.05,0.070000,0.130718,1018,1003,1.876954,True,REGULAR,USD
18,AAPL260529C00260000,2026-05-29 19:38:08+00:00,260.0,52.00,50.90,53.50,0.299999,0.580269,41,474,1.628908,True,REGULAR,USD
19,AAPL260529C00262500,2026-05-29 19:11:27+00:00,262.5,48.34,48.20,51.20,0.200001,0.415457,2,3,1.554690,True,REGULAR,USD
20,AAPL260529C00265000,2026-05-29 19:35:19+00:00,265.0,47.40,46.30,47.95,0.850002,1.825999,524,1523,1.335941,True,REGULAR,USD
21,AAPL260529C00267500,2026-05-29 18:00:50+00:00,267.5,42.83,43.20,46.45,-0.969997,-2.214606,225,53,1.554690,True,REGULAR,USD
22,AAPL260529C00270000,2026-05-29 19:56:49+00:00,270.0,42.25,41.60,42.25,-0.250000,-0.588235,395,1839,1.396487,True,REGULAR,USD
23,AAPL260529C00272500,2026-05-29 19:28:38+00:00,272.5,39.25,38.40,41.00,0.959999,2.507179,79,100,1.259769,True,REGULAR,USD
24,AAPL260529C00275000,2026-05-29 19:49:07+00:00,275.0,37.70,36.60,38.45,1.560001,4.316551,219,1167,1.464846,True,REGULAR,USD
25,AAPL260529C00277500,2026-05-29 19:51:33+00:00,277.5,34.81,33.45,36.45,0.090000,0.259217,156,166,1.332035,True,REGULAR,USD
26,AAPL260529C00280000,2026-05-29 19:51:01+00:00,280.0,32.55,31.55,33.45,1.099999,3.497610,590,2156,1.279300,True,REGULAR,USD
27,AAPL260529C00282500,2026-05-29 19:24:52+00:00,282.5,28.24,28.20,31.45,0.250000,0.893176,280,222,1.080083,True,REGULAR,USD
28,AAPL260529C00285000,2026-05-29 19:47:55+00:00,285.0,27.36,26.10,28.30,0.010000,0.036564,790,1647,0.894532,True,REGULAR,USD
29,AAPL260529C00287500,2026-05-29 19:30:46+00:00,287.5,23.84,23.80,26.00,-0.420000,-1.731245,79,194,0.968750,True,REGULAR,USD
30,AAPL260529C00290000,2026-05-29 19:57:14+00:00,290.0,22.59,21.70,23.45,0.010000,0.044288,2383,5837,0.973633,True,REGULAR,USD
31,AAPL260529C00292500,2026-05-29 19:38:22+00:00,292.5,19.01,19.15,20.30,0.309999,1.657751,441,674,0.695316,True,REGULAR,USD
32,AAPL260529C00295000,2026-05-29 19:56:48+00:00,295.0,17.25,16.70,17.30,-0.950001,-5.219784,707,4686,0.666996,True,REGULAR,USD
33,AAPL260529C00297500,2026-05-29 19:47:07+00:00,297.5,15.19,13.75,15.10,1.440000,10.472724,179,617,0.712893,True,REGULAR,USD
34,AAPL260529C00300000,2026-05-29 19:59:42+00:00,300.0,12.10,11.75,12.35,-0.500000,-3.968254,2855,17325,0.526860,True,REGULAR,USD
35,AAPL260529C00302500,2026-05-29 19:59:36+00:00,302.5,9.69,9.15,10.30,0.160000,1.678907,371,2213,0.579594,True,REGULAR,USD
36,AAPL260529C00305000,2026-05-29 19:59:02+00:00,305.0,6.99,6.70,7.80,-0.640000,-8.387946,3910,5666,0.474615,True,REGULAR,USD
37,AAPL260529C00307500,2026-05-29 19:59:02+00:00,307.5,4.50,4.25,4.80,-0.720000,-13.793099,3304,3233,0.242683,True,REGULAR,USD
38,AAPL260529C00310000,2026-05-29 19:59:58+00:00,310.0,1.87,1.88,2.33,-1.140000,-37.873753,59914,17332,0.149423,True,REGULAR,USD
39,AAPL260529C00312500,2026-05-29 19:59:42+00:00,312.5,0.05,0.03,0.08,-1.380000,-96.503500,169371,20111,0.036631,False,REGULAR,USD
40,AAPL260529C00315000,2026-05-29 19:57:06+00:00,315.0,0.01,0.00,0.01,-0.530000,-98.148150,161307,31264,0.085947,False,REGULAR,USD
41,AAPL260529C00317500,2026-05-29 19:58:38+00:00,317.5,0.01,0.00,0.01,-0.180000,-94.736850,55148,18279,0.144540,False,REGULAR,USD
42,AAPL260529C00320000,2026-05-29 19:54:21+00:00,320.0,0.01,0.00,0.01,-0.050000,-83.333336,22545,24278,0.203133,False,REGULAR,USD
43,AAPL260529C00322500,2026-05-29 19:55:36+00:00,322.5,0.01,0.00,0.01,-0.020000,-66.666670,3759,13071,0.257820,False,REGULAR,USD
44,AAPL260529C00325000,2026-05-29 19:54:50+00:00,325.0,0.02,0.00,0.01,0.000000,0.000000,840,7834,0.312507,False,REGULAR,USD
45,AAPL260529C00327500,2026-05-29 19:01:07+00:00,327.5,0.01,0.00,0.01,0.000000,0.000000,334,2002,0.359381,False,REGULAR,USD
46,AAPL260529C00330000,2026-05-29 19:21:13+00:00,330.0,0.01,0.00,0.01,0.000000,0.000000,728,2102,0.406256,False,REGULAR,USD
47,AAPL260529C00335000,2026-05-29 18:09:10+00:00,335.0,0.01,0.00,0.01,0.000000,0.000000,24,1611,0.507817,False,REGULAR,USD
48,AAPL260529C00340000,2026-05-29 18:58:45+00:00,340.0,0.01,0.00,0.01,0.000000,0.000000,31,1654,0.562504,False,REGULAR,USD
49,AAPL260529C00345000,2026-05-29 14:20:51+00:00,345.0,0.01,0.00,0.01,0.000000,0.000000,6,663,0.656253,False,REGULAR,USD
50,AAPL260529C00350000,2026-05-29 14:20:51+00:00,350.0,0.01,0.00,0.01,0.000000,0.000000,35,1439,0.734378,False,REGULAR,USD
51,AAPL260529C00355000,2026-05-19 18:07:50+00:00,355.0,0.03,0.00,0.02,0.020000,200.000000,1,82,0.859376,False,REGULAR,USD
52,AAPL260529C00360000,2026-05-26 13:36:53+00:00,360.0,0.02,0.00,0.01,0.000000,0.000000,2,10,0.906251,False,REGULAR,USD
53,AAPL260529C00365000,2026-05-28 16:21:53+00:00,365.0,0.11,0.00,0.02,0.000000,0.000000,1,82,1.031255,False,REGULAR,USD
54,AAPL260529C00370000,2026-05-28 17:17:20+00:00,370.0,0.05,0.00,0.02,0.000000,0.000000,28,233,1.109379,False,REGULAR,USD
55,AAPL260529C00375000,2026-05-28 19:30:36+00:00,375.0,0.10,0.00,0.02,0.000000,0.000000,1,7,1.187504,False,REGULAR,USD
56,AAPL260529C00380000,2026-05-28 19:30:03+00:00,380.0,0.10,0.00,0.02,0.000000,0.000000,4,35,1.281254,False,REGULAR,USD
57,AAPL260529C00385000,2026-05-28 16:55:39+00:00,385.0,0.01,0.00,0.02,0.000000,0.000000,1,17,1.343753,False,REGULAR,USD
58,AAPL260529C00390000,2026-05-28 13:35:17+00:00,390.0,0.04,0.00,0.02,0.000000,0.000000,1,111,1.421878,False,REGULAR,USD
59,AAPL260529C00400000,2026-05-28 18:06:46+00:00,400.0,0.01,0.00,0.01,0.000000,0.000000,13,16,1.500002,False,REGULAR,USD

In [15]:
yf.Ticker("SPY").funds_data.sector_weightings

{'realestate': 0.0194,
 'consumer_cyclical': 0.1025,
 'basic_materials': 0.018,
 'consumer_defensive': 0.048499998,
 'technology': 0.35860002,
 'communication_services': 0.11350001,
 'financial_services': 0.1179,
 'utilities': 0.023699999,
 'industrials': 0.0783,
 'energy': 0.0355,
 'healthcare': 0.0841}

In [17]:
yf.Ticker("QQQ").funds_data.top_holdings

# .description

                              Name  Holding Percent
Symbol
NVDA                   NVIDIA Corp         0.085321
AAPL                     Apple Inc         0.070088
MSFT                Microsoft Corp         0.053274
AMZN                Amazon.com Inc         0.050061
GOOGL         Alphabet Inc Class A         0.039415
GOOG          Alphabet Inc Class C         0.036542
AVGO                  Broadcom Inc         0.034820
TSLA                     Tesla Inc         0.033512
META    Meta Platforms Inc Class A         0.031752
WMT                    Walmart Inc         0.031317

In [21]:
yf.Tickers(["AAPL", "GOOG", "NVDA"]).tickers["NVDA"].history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-04-30 00:00:00-04:00,209.929993,210.300003,198.699997,199.570007,225239200,0.0,0.0
2026-05-01 00:00:00-04:00,201.279999,203.000000,197.119995,198.449997,128647000,0.0,0.0
2026-05-04 00:00:00-04:00,199.500000,201.729996,194.740005,198.479996,125368100,0.0,0.0
2026-05-05 00:00:00-04:00,199.300003,200.240005,196.029999,196.500000,113406600,0.0,0.0
2026-05-06 00:00:00-04:00,199.889999,208.270004,198.610001,207.830002,188362800,0.0,0.0
2026-05-07 00:00:00-04:00,208.339996,214.199997,206.500000,211.500000,168307900,0.0,0.0
2026-05-08 00:00:00-04:00,213.029999,217.800003,212.889999,215.199997,136421400,0.0,0.0
2026-05-11 00:00:00-04:00,214.039993,222.300003,213.889999,219.440002,160685800,0.0,0.0
2026-05-12 00:00:00-04:00,218.550003,223.750000,214.919998,220.779999,159176600,0.0,0.0
2026-05-13 00:00:00-04:00,224.929993,227.839996,221.570007,225.830002,150405400,0.0,0.0
2026-05-14 00:00:00-04:00,229.850006,236.539993,229.300003,235.740005,180782900,0.0,0.0
2026-05-15 00:00:00-04:00,229.759995,231.500000,224.240005,225.320007,180977600,0.0,0.0
2026-05-18 00:00:00-04:00,229.869995,230.000000,218.369995,222.320007,146280900,0.0,0.0
2026-05-19 00:00:00-04:00,219.619995,224.479996,217.910004,220.610001,140948200,0.0,0.0
2026-05-20 00:00:00-04:00,223.179993,226.130005,220.500000,223.470001,184201600,0.0,0.0
2026-05-21 00:00:00-04:00,222.289993,227.399994,217.929993,219.509995,203381800,0.0,0.0
2026-05-22 00:00:00-04:00,220.899994,221.009995,214.800003,215.330002,169275700,0.0,0.0
2026-05-26 00:00:00-04:00,216.539993,218.179993,212.000000,214.860001,187202600,0.0,0.0
2026-05-27 00:00:00-04:00,214.119995,214.149994,208.779999,212.600006,167601200,0.0,0.0
2026-05-28 00:00:00-04:00,211.279999,215.520004,211.220001,214.250000,143996000,0.0,0.0
2026-05-29 00:00:00-04:00,214.449997,217.859894,211.130005,211.139999,230465710,0.0,0.0

In [ ]:
# returns direct stock data as a df

yf.download(["AAPL", "GOOG", "NVDA"])

In [25]:
yf.Market("US").status

{'id': 'us',
 'name': 'U.S. markets',
 'status': 'closed',
 'yfit_market_id': 'us_market',
 'close': datetime.datetime(2026, 5, 29, 20, 0, tzinfo=datetime.timezone.utc),
 'message': 'U.S. markets closed',
 'open': datetime.datetime(2026, 5, 29, 13, 30, tzinfo=datetime.timezone.utc),
 'yfit_market_status': 'YFT_MARKET_CLOSED',
 'timezone': {'dst': 'true',
  'gmtoffset': '-14400',
  'short': 'EDT',
  '$text': 'America/New_York'},
 'tz': datetime.timezone(datetime.timedelta(days=-1, seconds=34560), 'EDT')}

In [29]:
yf.Sector("technology").industries

# top_companies, top_etfs, etc

,name,symbol,market weight
key,,,
semiconductors,Semiconductors,^YH31130020,0.395527
software-infrastructure,Software - Infrastructure,^YH31110030,0.200269
consumer-electronics,Consumer Electronics,^YH31120030,0.159766
software-application,Software - Application,^YH31110020,0.064386
computer-hardware,Computer Hardware,^YH31120020,0.043923
semiconductor-equipment-materials,Semiconductor Equipment & Materials,^YH31130010,0.042898
communication-equipment,Communication Equipment,^YH31120010,0.031480
information-technology-services,Information Technology Services,^YH31110010,0.023564
electronic-components,Electronic Components,^YH31120040,0.023235
scientific-technical-instruments,Scientific & Technical Instruments,^YH31120060,0.010509
solar,Solar,^YH31130030,0.002851
electronics-computer-distribution,Electronics & Computer Distribution,^YH31120050,0.001592

In [31]:
yf.Industry("semiconductors").top_companies

                                             name      rating  market weight
symbol
NVDA                           NVIDIA Corporation  Strong Buy       0.461277
AVGO                                Broadcom Inc.  Strong Buy       0.177103
MU                        Micron Technology, Inc.  Strong Buy       0.089559
AMD                  Advanced Micro Devices, Inc.  Strong Buy       0.072828
INTC                            Intel Corporation        Hold       0.055027
TXN                Texas Instruments Incorporated         Buy       0.026208
QCOM                        QUALCOMM Incorporated        Hold       0.023246
ADI                          Analog Devices, Inc.         Buy       0.018130
MRVL                     Marvell Technology, Inc.  Strong Buy       0.016162
NXPI                      NXP Semiconductors N.V.         Buy       0.007445
MPWR               Monolithic Power Systems, Inc.  Strong Buy       0.007242
ALAB                            Astera Labs, Inc.         Buy       0.004842
MCHP            Microchip Technology Incorporated         Buy       0.004711
CBRS                        Cerebras Systems Inc.         NaN       0.004705
ON                   ON Semiconductor Corporation         Buy       0.004377
GFS                          GLOBALFOUNDRIES Inc.         Buy       0.004373
CRDO           Credo Technology Group Holding Ltd  Strong Buy       0.003624
MTSI    MACOM Technology Solutions Holdings, Inc.         Buy       0.002771
LSCC            Lattice Semiconductor Corporation  Strong Buy       0.001826
SITM                           SiTime Corporation  Strong Buy       0.001739
RMBS                                  Rambus Inc.  Strong Buy       0.001507
SMTC                          Semtech Corporation  Strong Buy       0.001358
SWKS                     Skyworks Solutions, Inc.        Hold       0.001112
QRVO                                  Qorvo, Inc.        Hold       0.000844
ALGM                   Allegro MicroSystems, Inc.  Strong Buy       0.000838
CRUS                           Cirrus Logic, Inc.         Buy       0.000799
MXL                               MaxLinear, Inc.         Buy       0.000763
NVTS            Navitas Semiconductor Corporation        Hold       0.000659
SLAB                    Silicon Laboratories Inc.        Hold       0.000640
VSH                  Vishay Intertechnology, Inc.        Hold       0.000608
SYNA                       Synaptics Incorporated         Buy       0.000505
DIOD                          Diodes Incorporated  Strong Buy       0.000441
PI                                   Impinj, Inc.         Buy       0.000431
POWI                     Power Integrations, Inc.         Buy       0.000415
LASR                                 nLIGHT, Inc.  Strong Buy       0.000408
WOLF                              Wolfspeed, Inc.        Hold       0.000315
POET                       POET Technologies Inc.  Strong Buy       0.000204
SKYT                    SkyWater Technology, Inc.        Hold       0.000163
AMBQ                                          NaN         Buy       0.000158
AIP                                 Arteris, Inc.  Strong Buy       0.000155
AOSL        Alpha and Omega Semiconductor Limited        Hold       0.000127
CEVA                                   CEVA, Inc.  Strong Buy       0.000103
MRAM                  Everspin Technologies, Inc.  Strong Buy       0.000068
NVEC                              NVE Corporation        Hold       0.000041
ALMU                                 Aeluma, Inc.  Strong Buy       0.000040
QUIK                       QuickLogic Corporation         Buy       0.000036
GSIT                         GSI Technology, Inc.        Hold       0.000034
MX            Magnachip Semiconductor Corporation  Strong Buy       0.000021
IPWR                             Ideal Power Inc.  Strong Buy       0.000010
PXLW                             Pixelworks, Inc.  Strong Buy       0.000004

In [ ]:
calendars = yf.Calendars(start="2026-04-01", end="2026-05-01")
calendars.earnings_calendar

# economic_events, ipo_info_calendar, splits_calendar, calendars, etc

,Company,Marketcap,Event Name,Event Start Date,Timing,EPS Estimate,Reported EPS,Surprise(%)
Symbol,,,,,,,,
AAPL,Apple Inc.,4.439253e+12,None,2026-04-30 20:30:00+00:00,TAS,1.94,2.01,3.46
MSFT,Microsoft Corporation,3.127817e+12,None,2026-04-29 20:03:31+00:00,TAS,4.06,4.27,5.22
GOOGL,Alphabet Inc.,4.712302e+12,None,2026-04-29 20:01:35+00:00,TAS,2.67,5.11,91.59
GOOG,Alphabet Inc.,4.663113e+12,None,2026-04-29 20:01:35+00:00,TAS,2.63,5.11,94.30
AMZN,"Amazon.com, Inc.",2.850204e+12,None,2026-04-29 20:01:00+00:00,TAS,1.65,2.78,68.18
META,"Meta Platforms, Inc.",1.535898e+12,None,2026-04-29 20:01:00+00:00,TAS,6.66,10.44,56.79
KO,The Coca-Cola Company,3.508675e+11,None,2026-04-28 11:00:30+00:00,TAS,0.81,0.86,5.88
INTC,Intel Corporation,5.979181e+11,None,2026-04-23 20:01:00+00:00,TAS,0.01,0.29,2108.68
TSLA,"Tesla, Inc.",1.567113e+12,None,2026-04-22 20:10:44+00:00,TAS,0.35,0.41,17.15
NFLX,"Netflix, Inc.",3.709292e+11,None,2026-04-16 20:01:58+00:00,TAS,1.25,1.23,-1.40
TSM,Taiwan Semiconductor Manufacturing Company Lim...,2.082992e+12,None,2026-04-16 00:00:00+00:00,TAS,3.33,3.49,4.68
BAC,Bank of America Corporation,5.116980e+11,None,2026-04-15 10:44:44+00:00,TAS,1.02,1.11,8.78

In [36]:
yf.Lookup("apple").stock

,exchange,industryLink,industryName,quoteType,rank,regularMarketChange,regularMarketPercentChange,regularMarketPrice,shortName
symbol,,,,,,,,,
AAPL,NMS,https://finance.yahoo.com/sector/technology,Technology,equity,31737,-0.450012,-0.143999,312.059998,Apple Inc.
APLE,NYQ,https://finance.yahoo.com/sector/real_estate,Real Estate,equity,20047,-0.210000,-1.409400,14.690000,"Apple Hospitality REIT, Inc."
APC.F,FRA,https://finance.yahoo.com/sector/technology,Technology,equity,20015,-2.000000,-0.746269,266.000000,Apple Inc. R
APC.DE,GER,https://finance.yahoo.com/sector/technology,Technology,equity,20014,-0.299988,-0.112229,267.000000,Apple Inc. R
2788.T,JPX,https://finance.yahoo.com/sector/consumer_cycl...,Consumer Cyclical,equity,20003,0.000000,0.000000,378.000000,APPLE INTERNATIONAL CO LTD
4AAPL.TI,TLO,NaN,NaN,equity,20002,0.350006,0.130599,268.350006,APPLE
0R2V.L,LSE,https://finance.yahoo.com/sector/technology,Technology,equity,20002,-0.640015,-0.205991,310.059998,APPLE INC APPLE ORD
AAPL.BA,BUE,https://finance.yahoo.com/sector/technology,Technology,equity,20002,10.000000,0.043215,23150.000000,APPLE INC CEDEAR(REPR 1/20 SHR)
APRU,PNK,https://finance.yahoo.com/sector/consumer_defe...,Consumer Defensive,equity,20001,0.000000,0.000000,0.000100,"Apple Rush Co., Inc."
GAPJ,PNK,https://finance.yahoo.com/sector/energy,Energy,equity,20001,0.000000,0.000000,0.000100,GOLDEN APPLE OIL & GAS INC
3APE.DE,GER,NaN,NaN,equity,20001,0.389999,0.326059,120.000000,Leverage Shares PLC E
AAPI,OQB,https://finance.yahoo.com/sector/consumer_cycl...,Consumer Cyclical,equity,20001,0.000000,0.000000,0.120000,Apple iSports Group Inc.
APCD.XD,DXE,NaN,NaN,equity,20001,-0.400024,-0.149430,267.299988,Apple Inc
APC.HM,HAM,https://finance.yahoo.com/sector/technology,Technology,equity,20001,0.149994,0.056283,266.649994,Apple Inc. R
US03784Y2000.SG,STU,NaN,NaN,equity,20001,-0.250000,-1.951600,12.560000,Apple Hospitality REIT Inc.
AAPL.NE,NEO,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.070000,-0.158191,44.180000,APPLE CDR (CAD HEDGED)
1AAPL.MI,MIL,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.299988,-0.112250,266.950012,APPLE
APC8.MU,MUN,https://finance.yahoo.com/sector/technology,Technology,equity,20001,0.000000,0.000000,27.400000,Apple Inc. R
AAPL.VI,VIE,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.450012,-0.168260,267.000000,APPLE INC
APC.HA,HAN,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.949982,-0.355067,266.600006,Apple Inc. R
APC.SG,STU,https://finance.yahoo.com/sector/technology,Technology,equity,20001,-0.750000,-0.279590,267.500000,Apple Inc.
APC8.F,FRA,https://finance.yahoo.com/sector/technology,Technology,equity,20001,0.000000,0.000000,26.799999,Apple Inc. R
AAPLC.BA,BUE,NaN,NaN,equity,20001,0.630001,4.067147,16.120001,APPLE INC CEDEAR(REPR 1/20 SHR)
D90.F,FRA,https://finance.yahoo.com/sector/consumer_cycl...,Consumer Cyclical,equity,20001,0.000000,0.000000,1.990000,Apple International Co. Ltd. R
AAPL34.SA,SAO,https://finance.yahoo.com/sector/technology,Technology,equity,20001,0.389999,0.497385,78.800003,APPLE DRN

In [40]:
results = yf.Search("nvidia", max_results=3, news_count=3)

results.quotes

# news, etc

[{'exchange': 'NMS',
  'shortname': 'NVIDIA Corporation',
  'quoteType': 'EQUITY',
  'symbol': 'NVDA',
  'index': 'quotes',
  'score': 34638.0,
  'typeDisp': 'Equity',
  'longname': 'NVIDIA Corporation',
  'exchDisp': 'NASDAQ',
  'sector': 'Technology',
  'sectorDisp': 'Technology',
  'industry': 'Semiconductors',
  'industryDisp': 'Semiconductors',
  'dispSecIndFlag': True,
  'isYahooFinance': True,
  'prevName': 'Usual Stablecoin',
  'nameChangeDate': '2026-05-29'},
 {'exchange': 'NEO',
  'shortname': 'NVIDIA (NVDA) YIELD SHARES PURP',
  'quoteType': 'ETF',
  'symbol': 'YNVD.NE',
  'index': 'quotes',
  'score': 20011.0,
  'typeDisp': 'ETF',
  'exchDisp': 'NEO',
  'isYahooFinance': True},
 {'exchange': 'BTS',
  'shortname': 'T-Rex 2X Long NVIDIA Daily Targ',
  'quoteType': 'ETF',
  'symbol': 'NVDX',
  'index': 'quotes',
  'score': 20007.0,
  'typeDisp': 'ETF',
  'exchDisp': 'BATS Trading',
  'isYahooFinance': True}]

In [45]:
q = yf.EquityQuery(
    "and", [
        yf.EquityQuery("eq", ["region", "us"]),
        yf.EquityQuery("gt", ["percentchange", 3])
    ]
)

results = yf.screen(q, sortField="percentchange", sortAsc=False)

results

{'start': 0,
 'count': 25,
 'total': 1871,
 'quotes': [{'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 587353890,
   'impliedSharesOutstanding': 587353890,
   'bookValue': 0.0152271,
   'fiftyDayAverage': 0.00608,
   'fiftyDayAverageChange': 0.87392,
   'fiftyDayAverageChangePercent': 143.73685,
   'twoHundredDayAverage': 0.012935,
   'twoHundredDayAverageChange': 0.867065,
   'twoHundredDayAverageChangePercent': 67.03247,
   'priceToBook': 57.791702,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'earningsTimestampStart': 1756361740,
   'marketState': 'POST',
   'epsTrailingTwelveMonths': -0.01,
   'bidSize': 10000,
   'askSize': 1000,
   'market': 'us_market',
   'messageBoardId': 'finmb_26687808',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'Eden Innovations Ltd',
   'regularMarketOpen': 0.88,
   'averageDailyVolume3Month': 10,
   'averageDailyVolume10Day': 0,
   'regularMarketChangePercent': 73232.09,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1423578600000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.879,
   'fiftyTwoWeekLowChangePercent': 878.99994,
   'fiftyTwoWeekRange': '0.001 - 0.88',
   'fiftyTwoWeekHighChange': 0.0,
   'fiftyTwoWeekHighChangePercent': 0.0,
   'fiftyTwoWeekChangePercent': -99.38144,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.8788,
   'regularMarketTime': 1780063075,
   'regularMarketPrice': 0.88,
   'regularMarketDayHigh': 0.88,
   'regularMarketDayRange': '0.88 - 0.88',
   'regularMarketDayLow': 0.88,
   'regularMarketVolume': 1000,
   'regularMarketPreviousClose': 0.0012,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.002,
   'marketCap': 516871456,
   'earningsTimestampEnd': 1756707340,
   'isEarningsDateEstimate': True,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.88,
   'fiftyTwoWeekLow': 0.001,
   'financialCurrency': 'AUD',
   'shortName': 'Eden Energy, Ltd.',
   'ask': 0.9,
   'displayName': 'Eden Innovations',
   'symbol': 'EDEYF'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 65973830,
   'impliedSharesOutstanding': 65973830,
   'bookValue': -0.048,
   'fiftyDayAverage': 0.00023204,
   'fiftyDayAverageChange': 0.0017679601,
   'fiftyDayAverageChangePercent': 7.6192045,
   'twoHundredDayAverage': 0.0001785706,
   'twoHundredDayAverageChange': 0.0018214295,
   'twoHundredDayAverageChangePercent': 10.200052,
   'forwardPE': -0.0031746035,
   'priceToBook': -0.041666668,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': -0.1,
   'epsForward': -0.63,
   'bidSize': 0,
   'askSize': 0,
   'market': 'us_market',
   'messageBoardId': 'finmb_130914666',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'Sugarmade, Inc.',
   'regularMarketOpen': 0.0001,
   'averageDailyVolume3Month': 20716,
   'averageDailyVolume10Day': 49990,
   'regularMarketChangePercent': 1900.0001,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1699453800000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.001999,
   'fiftyTwoWeekLowChangePercent': 1999.0001,
   'fiftyTwoWeekRange': '1.0E-6 - 0.1',
   'fiftyTwoWeekHighChange': -0.098000005,
   'fiftyTwoWeekHighChangePercent': -0.98,
   'fiftyTwoWeekChangePercent': 100.0,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.0019000001,
   'regularMarketTime': 1779480000,
   'regularMarketPrice': 0.002,
   'regularMarketDayHigh': 0.0001,
   'regularMarketDayRange': '1.0E-4 - 1.0E-4',
   'regularMarketDayLow': 0.0001,
   'regularMarketVolume': 473,
   'regularMarketPreviousClose': 0.0001,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.003,
   'marketCap': 131947,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.1,
   'fiftyTwoWeekLow': 1e-06,
   'financialCurrency': 'USD',
   'shortName': 'Sugarmade, Inc.',
   'ask': 0.0045,
   'displayName': 'Sugarmade',
   'symbol': 'SGMD'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 182478992,
   'impliedSharesOutstanding': 182478992,
   'bookValue': 2.0452008,
   'fiftyDayAverage': 0.080904,
   'fiftyDayAverageChange': 0.219096,
   'fiftyDayAverageChangePercent': 2.7080986,
   'twoHundredDayAverage': 0.21279,
   'twoHundredDayAverageChange': 0.087210014,
   'twoHundredDayAverageChangePercent': 0.40984076,
   'priceToBook': 0.14668487,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': 0.09,
   'bidSize': 0,
   'askSize': 0,
   'market': 'us_market',
   'messageBoardId': 'finmb_9203811',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'Grupo Mexicano de Desarrollo, S.A.B.',
   'regularMarketOpen': 0.77,
   'averageDailyVolume3Month': 87,
   'averageDailyVolume10Day': 285,
   'regularMarketChangePercent': 1644.1862,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1255959000000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.28280002,
   'fiftyTwoWeekLowChangePercent': 16.44186,
   'fiftyTwoWeekRange': '0.0172 - 0.77',
   'fiftyTwoWeekHighChange': -0.46999997,
   'fiftyTwoWeekHighChangePercent': -0.6103896,
   'fiftyTwoWeekChangePercent': -38.77551,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.28280002,
   'regularMarketTime': 1779998400,
   'regularMarketPrice': 0.3,
   'regularMarketDayHigh': 0.77,
   'regularMarketDayRange': '0.77 - 0.77',
   'regularMarketDayLow': 0.77,
   'regularMarketVolume': 24,
   'regularMarketPreviousClose': 0.0172,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.0,
   'marketCap': 54743700,
   'trailingAnnualDividendRate': 0.0,
   'trailingPE': 3.3333333,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.77,
   'fiftyTwoWeekLow': 0.0172,
   'financialCurrency': 'MXN',
   'shortName': 'GRUPO MEXICANO DE DESARROLLO SA',
   'ask': 0.0,
   'displayName': 'Grupo Mexicano de Desarrollo, S.A.B',
   'symbol': 'GMXDF'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 89815573,
   'impliedSharesOutstanding': 89819773,
   'bookValue': 22.233,
   'fiftyDayAverage': 0.005922,
   'fiftyDayAverageChange': -0.0010219999,
   'fiftyDayAverageChangePercent': -0.17257681,
   'twoHundredDayAverage': 0.008298334,
   'twoHundredDayAverageChange': -0.0033983337,
   'twoHundredDayAverageChangePercent': -0.40952,
   'priceToBook': 0.0002203931,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': -12.5,
   'bidSize': 12688,
   'askSize': 13000,
   'market': 'us_market',
   'messageBoardId': 'finmb_1945675776',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'Tian Ruixiang Holdings Ltd.',
   'regularMarketOpen': 0.0003,
   'averageDailyVolume3Month': 2654848,
   'averageDailyVolume10Day': 136509,
   'regularMarketChangePercent': 1533.3333,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1772461800000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.0046,
   'fiftyTwoWeekLowChangePercent': 15.333333,
   'fiftyTwoWeekRange': '3.0E-4 - 0.0602',
   'fiftyTwoWeekHighChange': -0.055299997,
   'fiftyTwoWeekHighChangePercent': -0.9186046,
   'fiftyTwoWeekChangePercent': -99.30796,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.0046,
   'regularMarketTime': 1779480000,
   'regularMarketPrice': 0.0049,
   'regularMarketDayHigh': 0.0003,
   'regularMarketDayRange': '3.0E-4 - 3.0E-4',
   'regularMarketDayLow': 0.0003,
   'regularMarketVolume': 6325,
   'regularMarketPreviousClose': 0.0003,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.004,
   'marketCap': 440116,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.0602,
   'fiftyTwoWeekLow': 0.0003,
   'financialCurrency': 'USD',
   'shortName': 'TIAN RUIXIANG Holdings Ltd',
   'ask': 0.0049,
   'displayName': 'Tian Ruixiang',
   'symbol': 'TIRXF'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 677350021,
   'impliedSharesOutstanding': 677350021,
   'bookValue': -3.156,
   'fiftyDayAverage': 1.18e-05,
   'fiftyDayAverageChange': 8.8199995e-05,
   'fiftyDayAverageChangePercent': 7.474576,
   'twoHundredDayAverage': 1.045e-05,
   'twoHundredDayAverageChange': 8.955e-05,
   'twoHundredDayAverageChangePercent': 8.569378,
   'priceToBook': -3.168568e-05,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': 0.0,
   'bidSize': 0,
   'askSize': 0,
   'market': 'us_market',
   'messageBoardId': 'finmb_26477666',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'South American Gold Corp.',
   'regularMarketOpen': 1e-06,
   'averageDailyVolume3Month': 403,
   'averageDailyVolume10Day': 2500,
   'regularMarketChangePercent': 900.00006,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1285594200000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 9.9e-05,
   'fiftyTwoWeekLowChangePercent': 99.0,
   'fiftyTwoWeekRange': '1.0E-6 - 1.0E-4',
   'fiftyTwoWeekHighChange': 0.0,
   'fiftyTwoWeekHighChangePercent': 0.0,
   'fiftyTwoWeekChangePercent': 900.0,
   'gmtOffSetMilliseconds': -14400000,
   'prevName': 'Sativa Growth International',
   'nameChangeDate': '2026-05-29',
   'priceHint': 4,
   'regularMarketChange': 9e-05,
   'regularMarketTime': 1779998400,
   'regularMarketPrice': 0.0001,
   'regularMarketDayHigh': 1e-06,
   'regularMarketDayRange': '1.0E-6 - 1.0E-6',
   'regularMarketDayLow': 1e-06,
   'regularMarketVolume': 16000,
   'regularMarketPreviousClose': 1e-05,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.0,
   'marketCap': 67735,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.0001,
   'fiftyTwoWeekLow': 1e-06,
   'financialCurrency': 'USD',
   'shortName': 'SOUTH AMERICAN GOLD CORP',
   'ask': 0.0,
   'displayName': 'South American Gold',
   'symbol': 'SAGD'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 999556,
   'impliedSharesOutstanding': 999556,
   'bookValue': 0.014,
   'fiftyDayAverage': 0.010068,
   'fiftyDayAverageChange': -0.009068,
   'fiftyDayAverageChangePercent': -0.9006754,
   'twoHundredDayAverage': 0.0071585,
   'twoHundredDayAverageChange': -0.0061585,
   'twoHundredDayAverageChangePercent': -0.8603059,
   'priceToBook': 0.071428575,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': 0.0,
   'bidSize': 0,
   'askSize': 0,
   'market': 'us_market',
   'messageBoardId': 'finmb_208112764',
   'fullExchangeName': 'OTC Markets OTCID',
   'longName': 'American Heritage International Inc.',
   'regularMarketOpen': 0.001,
   'averageDailyVolume3Month': 72,
   'averageDailyVolume10Day': 0,
   'regularMarketChangePercent': 900.0,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1367587800000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.00090000004,
   'fiftyTwoWeekLowChangePercent': 9.000001,
   'fiftyTwoWeekRange': '1.0E-4 - 0.045',
   'fiftyTwoWeekHighChange': -0.044000003,
   'fiftyTwoWeekHighChangePercent': -0.97777784,
   'fiftyTwoWeekChangePercent': -50.0,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.00090000004,
   'regularMarketTime': 1779480000,
   'regularMarketPrice': 0.001,
   'regularMarketDayHigh': 0.001,
   'regularMarketDayRange': '0.001 - 0.001',
   'regularMarketDayLow': 0.001,
   'regularMarketVolume': 1,
   'regularMarketPreviousClose': 0.000100000005,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'OID',
   'bid': 0.005,
   'marketCap': 999,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.045,
   'fiftyTwoWeekLow': 0.0001,
   'financialCurrency': 'USD',
   'shortName': 'American Heritage International',
   'ask': 2.39,
   'displayName': 'American Heritage',
   'symbol': 'AHII'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 1364391500,
   'impliedSharesOutstanding': 1364391500,
   'bookValue': 0.19170777,
   'fiftyDayAverage': 0.425642,
   'fiftyDayAverageChange': 71.38435,
   'fiftyDayAverageChangePercent': 167.70984,
   'twoHundredDayAverage': 0.4443759,
   'twoHundredDayAverageChange': 71.36562,
   'twoHundredDayAverageChangePercent': 160.59743,
   'priceToBook': 374.5805,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'marketState': 'POST',
   'epsTrailingTwelveMonths': 0.03,
   'bidSize': 25000,
   'askSize': 100,
   'market': 'us_market',
   'messageBoardId': 'finmb_29383163',
   'fullExchangeName': 'OTC Markets OTCPK',
   'regularMarketOpen': 206.51,
   'averageDailyVolume3Month': 3,
   'averageDailyVolume10Day': 0,
   'regularMarketChangePercent': 786.7778,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1766586600000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 71.4069,
   'fiftyTwoWeekLowChangePercent': 177.14438,
   'fiftyTwoWeekRange': '0.4031 - 206.51',
   'fiftyTwoWeekHighChange': -134.7,
   'fiftyTwoWeekHighChangePercent': -0.65226865,
   'fiftyTwoWeekChangePercent': -59.69,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 2,
   'regularMarketChange': 70.81,
   'regularMarketTime': 1780079324,
   'regularMarketPrice': 71.81,
   'regularMarketDayHigh': 206.51,
   'regularMarketDayRange': '71.81 - 206.51',
   'regularMarketDayLow': 71.81,
   'regularMarketVolume': 903,
   'regularMarketPreviousClose': 1.0,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 206.51,
   'marketCap': 97976950784,
   'trailingAnnualDividendRate': 0.075,
   'trailingPE': 2393.6667,
   'dividendRate': 0.01,
   'trailingAnnualDividendYield': 0.075,
   'fiftyTwoWeekHigh': 206.51,
   'fiftyTwoWeekLow': 0.4031,
   'dividendYield': 2.39,
   'financialCurrency': 'HKD',
   'ask': 206.51,
   'displayName': 'L.K. Technology',
   'symbol': 'LKTEF'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 45195602,
   'impliedSharesOutstanding': 45195602,
   'bookValue': -0.7661719,
   'fiftyDayAverage': 0.08071846,
   'fiftyDayAverageChange': -0.020718459,
   'fiftyDayAverageChangePercent': -0.2566756,
   'twoHundredDayAverage': 0.08500518,
   'twoHundredDayAverageChange': -0.02500518,
   'twoHundredDayAverageChangePercent': -0.29416066,
   'priceToBook': -0.078311406,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'earningsTimestampStart': 1780344000,
   'marketState': 'POST',
   'epsTrailingTwelveMonths': -0.15,
   'bidSize': 10440,
   'askSize': 20000,
   'market': 'us_market',
   'messageBoardId': 'finmb_1920605',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'Eguana Technologies Inc.',
   'regularMarketOpen': 0.0599,
   'averageDailyVolume3Month': 6348,
   'averageDailyVolume10Day': 7020,
   'regularMarketChangePercent': 700.0,
   'hasPrePostMarketData': False,
   'firstTradeDateMilliseconds': 1744032600000,
   'corporateActions': [],
   'fiftyTwoWeekLowChange': 0.016199999,
   'fiftyTwoWeekLowChangePercent': 0.36986297,
   'fiftyTwoWeekRange': '0.0438 - 0.16407',
   'fiftyTwoWeekHighChange': -0.10406999,
   'fiftyTwoWeekHighChangePercent': -0.6343024,
   'fiftyTwoWeekChangePercent': -11.081868,
   'gmtOffSetMilliseconds': -14400000,
   'priceHint': 4,
   'regularMarketChange': 0.0525,
   'regularMarketTime': 1780072607,
   'regularMarketPrice': 0.06,
   'regularMarketDayHigh': 0.06,
   'regularMarketDayRange': '0.0599 - 0.06',
   'regularMarketDayLow': 0.0599,
   'regularMarketVolume': 20000,
   'regularMarketPreviousClose': 0.0075,
   'esgPopulated': False,
   'tradeable': False,
   'cryptoTradeable': False,
   'exchange': 'PNK',
   'bid': 0.0497,
   'marketCap': 2711736,
   'earningsTimestampEnd': 1780344000,
   'earningsCallTimestampStart': 1732921200,
   'earningsCallTimestampEnd': 1732921200,
   'isEarningsDateEstimate': True,
   'trailingAnnualDividendRate': 0.0,
   'trailingAnnualDividendYield': 0.0,
   'fiftyTwoWeekHigh': 0.16407,
   'fiftyTwoWeekLow': 0.0438,
   'financialCurrency': 'CAD',
   'shortName': 'Eguana Technologies Inc',
   'ask': 0.0684,
   'displayName': 'Eguana',
   'symbol': 'EGTYF'},
  {'language': 'en-US',
   'region': 'US',
   'quoteType': 'EQUITY',
   'typeDisp': 'Equity',
   'quoteSourceName': 'Delayed Quote',
   'triggerable': False,
   'customPriceAlertConfidence': 'LOW',
   'currency': 'USD',
   'sharesOutstanding': 22605669,
   'impliedSharesOutstanding': 22605669,
   'bookValue': -0.0763644,
   'fiftyDayAverage': 0.037786,
   'fiftyDayAverageChange': 0.16221401,
   'fiftyDayAverageChangePercent': 4.292966,
   'twoHundredDayAverage': 0.03041615,
   'twoHundredDayAverageChange': 0.16958386,
   'twoHundredDayAverageChangePercent': 5.575454,
   'priceToBook': -2.6190217,
   'sourceInterval': 15,
   'exchangeDataDelayedBy': 0,
   'exchangeTimezoneName': 'America/New_York',
   'exchangeTimezoneShortName': 'EDT',
   'dividendDate': 1470355200,
   'earningsTimestampStart': 1780084800,
   'marketState': 'POST',
   'epsTrailingTwelveMonths': -0.01,
   'bidSize': 70000,
   'askSize': 0,
   'market': 'us_market',
   'messageBoardId': 'finmb_115152019',
   'fullExchangeName': 'OTC Markets OTCPK',
   'longName': 'New Destiny Mining Corp.',
   'regularMarketOpen': 0.0342,
   'averageDailyVolume3Month': 370,
   'averageDailyVolume10Day': 300,

In [48]:
for item in results["quotes"]:
    print(item["symbol"], item.get("displayName"), item.get("regularMarketChangePercent"))

EDEYF Eden Innovations 73232.09
SGMD Sugarmade 1900.0001
GMXDF Grupo Mexicano de Desarrollo, S.A.B 1644.1862
TIRXF Tian Ruixiang 1533.3333
SAGD South American Gold 900.00006
AHII American Heritage 900.0
LKTEF L.K. Technology 786.7778
EGTYF Eguana 700.0
NDMCF New Destiny Mining 479.71008
ISOL 1mage Software 450.0
FUNFF FansUnite Entertainment 333.33328
THORF Thor Energy 304.7619
XINRY Xinyuan Real Estate 300.0
ASLRF Alien Metals 299.99997
BDLND Badlands Resources 272.43243
WRCDF None 266.66666
ZPAS Zoompass 249.99998
BDLNF Badlands Resources 249.99995
RBZHF Reebonz Holding 233.33333
VGLS SB Technology 222.58064
JAMGF Tuktu Resources 209.27834
ALCWF None 207.69234
ATVK Ameritek Ventures 166.66667
FFZY Fansfrenzy 166.66664
UNEH Universal New Energy Holding 164.95001

In [49]:
ws = yf.WebSocket()
ws.subscribe(["APPL", "GOOG", "NVDA", "MSFT"])
ws.listen(print)

Connected to WebSocket.
Subscribed to symbols: ['APPL', 'GOOG', 'NVDA', 'MSFT']
Listening for messages...
{'id': 'GOOG', 'price': 376.98, 'time': '1780098105000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': 0.14611436, 'change': 0.5500183, 'price_hint': '2'}
{'id': 'MSFT', 'price': 449.73, 'time': '1780098112000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': -0.113268316, 'change': -0.50997925, 'price_hint': '2'}
{'id': 'MSFT', 'price': 449.7382, 'time': '1780098118000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': -0.11145179, 'change': -0.50180054, 'price_hint': '2'}
{'id': 'GOOG', 'price': 376.98, 'time': '1780098123000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': 0.14611436, 'change': 0.5500183, 'price_hint': '2'}
{'id': 'MSFT', 'price': 449.738, 'time': '1780098120000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': -0.11149246, 'change': -0.50198364, 'price_hint': '2'}
{'id': 'GOOG', 'price': 376.98, 'time': '1780098124000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': 0.14611436, 'change': 0.5500183, 'price_hint': '2'}
{'id': 'MSFT', 'price': 449.7398, 'time': '1780098128000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': -0.11109255, 'change': -0.5001831, 'price_hint': '2'}
{'id': 'MSFT', 'price': 449.8, 'time': '1780098130000', 'exchange': 'NMS', 'quote_type': 8, 'market_hours': 2, 'change_percent': -0.0977262, 'change': -0.44000244, 'price_hint': '2'}
Received keyboard interrupt.
WebSocket connection closed.

In [ ]:
import asyncio

async def main():
    ws = yf.AsyncWebSocket(verbose=False)

    await ws.subscribe(["APPL", "GOOG", "NVDA", "MSFT"])

    async def on_message(msg):
        print(msg)

    await ws.listen(on_message)

asyncio.run(main())

# You can also use proxies by specifying yf.config.network.proxy = {"http": "proxy"}

RuntimeError: asyncio.run() cannot be called from a running event loop