Download SPY Data

In [9]:
import yfinance as yf
import pandas as pd
df = yf.download("SPY", period="5y")
df["SMA20"] = df["Close"].rolling(20).mean()
df["SMA50"] = df["Close"].rolling(50).mean()
df.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume,SMA20,SMA50
Ticker,SPY,SPY,SPY,SPY,SPY,,
2021-06-04,394.701202,395.000084,391.189417,392.973328,55938800,NaN,NaN
2021-06-07,394.318298,394.869345,393.384315,394.691886,51555000,NaN,NaN
2021-06-08,394.402313,395.270911,392.571715,395.177507,47134300,NaN,NaN
2021-06-09,393.813965,395.317692,393.589818,395.242958,48436300,NaN,NaN
2021-06-10,395.644440,396.597120,393.720437,395.037357,51020100,NaN,NaN

In [10]:
df["Buy"] = (df["SMA20"] > df["SMA50"]) & (df["SMA20"].shift(1) <= df["SMA50"].shift(1))
df["Sell"] = (df["SMA20"] < df["SMA50"]) & (df["SMA20"].shift(1) >= df["SMA50"].shift(1))
df.loc[df["Buy"] | df["Sell"], ["Buy", "Sell", "SMA20", "SMA50"]]

Price         Buy   Sell       SMA20       SMA50
Ticker
2021-10-01  False   True  415.074527  415.701669
2021-10-28   True  False  417.377060  417.258237
2022-01-25  False   True  437.048495  437.284800
2022-04-01   True  False  415.548685  415.504501
2022-05-02  False   True  412.480249  412.795288
2022-08-01   True  False  372.018968  371.577615
2022-09-16  False   True  382.162357  383.412539
2022-11-11   True  False  361.819217  360.648307
2023-01-03  False   True  371.389043  371.911331
2023-01-27   True  False  376.399442  376.307905
2023-03-14  False   True  382.681436  382.762736
2023-04-13   True  False  386.946297  386.322889
2023-08-28  False   True  428.976526  429.591591
2023-11-20   True  False  419.920076  419.492714
2024-04-26  False   True  497.817624  498.272996
2024-05-20   True  False  503.038568  502.201583
2024-08-09  False   True  531.456590  531.529626
2024-09-03   True  False  537.828976  537.573657
2025-01-14  False   True  583.021448  583.915842
2025-02-04   True  False  588.407910  588.400145
2025-03-07  False   True  587.773621  587.845372
2025-05-14   True  False  547.779005  546.917374
2026-03-02  False   True  685.529312  685.979954
2026-04-23   True  False  677.542502  675.592277

In [15]:
df["In Position"] = pd.NA
df.loc[df["Buy"], "In Position"] = True
df.loc[df["Sell"], "In Position"] = False
df["In Position"] = df["In Position"].ffill().fillna(False)
df.loc[df["In Position"], ["Buy", "Sell", "In Position", "Close"]].head(10)

Price         Buy   Sell In Position       Close
Ticker                                       SPY
2021-10-28   True  False        True  430.839325
2021-10-29  False  False        True  431.713593
2021-11-01  False  False        True  432.456268
2021-11-02  False  False        True  434.204742
2021-11-03  False  False        True  436.855652
2021-11-04  False  False        True  438.914307
2021-11-05  False  False        True  440.437164
2021-11-08  False  False        True  440.813202
2021-11-09  False  False        True  439.356110
2021-11-10  False  False        True  435.821564

In [43]:
df["Position Change"] = (df["In Position"] & df["Buy"]) | (~df["In Position"] & df["Sell"])

events = df.loc[df["Position Change"], ["Position Change", "Close", "Buy", "Sell"]]

entries = events.loc[df["Buy"], "Close"]
exits = events.loc[df["Sell"], "Close"]

trades = list(zip(list(entries.index), list(entries["SPY"]), list(exits.index), list(exits["SPY"])))
trades

[(Timestamp('2021-10-28 00:00:00'),
  430.8393249511719,
  Timestamp('2021-10-01 00:00:00'),
  408.203125),
 (Timestamp('2022-04-01 00:00:00'),
  428.5863342285156,
  Timestamp('2022-01-25 00:00:00'),
  409.854248046875),
 (Timestamp('2022-08-01 00:00:00'),
  390.37994384765625,
  Timestamp('2022-05-02 00:00:00'),
  392.2115478515625),
 (Timestamp('2022-11-11 00:00:00'),
  380.28424072265625,
  Timestamp('2022-09-16 00:00:00'),
  367.92657470703125),
 (Timestamp('2023-01-27 00:00:00'),
  388.90399169921875,
  Timestamp('2023-01-03 00:00:00'),
  365.07208251953125),
 (Timestamp('2023-04-13 00:00:00'),
  397.8846435546875,
  Timestamp('2023-03-14 00:00:00'),
  375.5309143066406),
 (Timestamp('2023-11-20 00:00:00'),
  440.30853271484375,
  Timestamp('2023-08-28 00:00:00'),
  427.65325927734375),
 (Timestamp('2024-05-20 00:00:00'),
  517.4664306640625,
  Timestamp('2024-04-26 00:00:00'),
  496.1844177246094),
 (Timestamp('2024-09-03 00:00:00'),
  540.7019653320312,
  Timestamp('2024-08-09 00:00:00'),
  522.0054931640625),
 (Timestamp('2025-02-04 00:00:00'),
  593.17529296875,
  Timestamp('2025-01-14 00:00:00'),
  573.8653564453125),
 (Timestamp('2025-05-14 00:00:00'),
  580.9304809570312,
  Timestamp('2025-03-07 00:00:00'),
  567.6849975585938),
 (Timestamp('2026-04-23 00:00:00'),
  708.4500122070312,
  Timestamp('2026-03-02 00:00:00'),
  684.5106201171875)]