Download SPY Data

In [14]:
import yfinance as yf
import pandas as pd
df = yf.download("SPY", period="5y")
df["SMA20"] = df["Close"].rolling(20).mean()
df["SMA50"] = df["Close"].rolling(50).mean()
df.head()

[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume,SMA20,SMA50
Ticker,SPY,SPY,SPY,SPY,SPY,,
2021-06-04,394.701202,395.000084,391.189417,392.973328,55938800,NaN,NaN
2021-06-07,394.318237,394.869284,393.384254,394.691825,51555000,NaN,NaN
2021-06-08,394.402313,395.270911,392.571715,395.177507,47134300,NaN,NaN
2021-06-09,393.813904,395.317631,393.589757,395.242897,48436300,NaN,NaN
2021-06-10,395.644501,396.597182,393.720498,395.037418,51020100,NaN,NaN

In [15]:
df["Buy"] = (df["SMA20"] > df["SMA50"]) & (df["SMA20"].shift(1) <= df["SMA50"].shift(1))
df["Sell"] = (df["SMA20"] < df["SMA50"]) & (df["SMA20"].shift(1) >= df["SMA50"].shift(1))
df.loc[df["Buy"] | df["Sell"], ["Buy", "Sell", "SMA20", "SMA50"]]

Price         Buy   Sell       SMA20       SMA50
Ticker
2021-10-01  False   True  415.074545  415.701681
2021-10-28   True  False  417.377052  417.258242
2022-01-25  False   True  437.048502  437.284807
2022-04-01   True  False  415.548672  415.504493
2022-05-02  False   True  412.480235  412.795274
2022-08-01   True  False  372.018958  371.577608
2022-09-16  False   True  382.162321  383.412523
2022-11-11   True  False  361.819218  360.648297
2023-01-03  False   True  371.389046  371.911331
2023-01-27   True  False  376.399435  376.307904
2023-03-14  False   True  382.681450  382.762740
2023-04-13   True  False  386.946309  386.322900
2023-08-28  False   True  428.976535  429.591599
2023-11-20   True  False  419.920082  419.492717
2024-04-26  False   True  497.817619  498.272991
2024-05-20   True  False  503.038556  502.201573
2024-08-09  False   True  531.456592  531.529623
2024-09-03   True  False  537.828990  537.573660
2025-01-14  False   True  583.021451  583.915841
2025-02-04   True  False  588.407907  588.400143
2025-03-07  False   True  587.773615  587.845370
2025-05-14   True  False  547.779005  546.917374
2026-03-02  False   True  685.529312  685.979954
2026-04-23   True  False  677.542502  675.592277

In [16]:
df["In Position"] = pd.NA
df.loc[df["Buy"], "In Position"] = 1
df.loc[df["Sell"], "In Position"] = 0
df["In Position"] = df["In Position"].ffill().fillna(0).astype(bool)
df.head()

Price,Close,High,Low,Open,Volume,SMA20,SMA50,Buy,Sell,In Position
Ticker,SPY,SPY,SPY,SPY,SPY,,,,,
2021-06-04,394.701202,395.000084,391.189417,392.973328,55938800,NaN,NaN,False,False,False
2021-06-07,394.318237,394.869284,393.384254,394.691825,51555000,NaN,NaN,False,False,False
2021-06-08,394.402313,395.270911,392.571715,395.177507,47134300,NaN,NaN,False,False,False
2021-06-09,393.813904,395.317631,393.589757,395.242897,48436300,NaN,NaN,False,False,False
2021-06-10,395.644501,396.597182,393.720498,395.037418,51020100,NaN,NaN,False,False,False